### PR TITLE
fix(decryption): ensure values are positive 

### LINKED ISSUE #2: Fix undeterminism
> key::tests::key_generation_128 has failed with "unwrap() on None". I've restarted the test and it got "fixed". IIUC you have non-determinism in your tests and implementation has a bug.

Ref: https://github.com/RustCrypto/RSA/pull/1#issuecomment-443662996

### PR DESCRIPTION
**Pull request by dignifiedquire**
When decrypting, care has to be taken to ensure that negative numbers are brought back into the positive range. 

In most cases the `if < 0 then += prime` was enough, but if the number was more negative than the prime, we ended up with still a negative number. So this was changed to use a `while` statement, which ensures the right thing always happens. 

Fixes #2

### CODE REVIEW

File: src/key.rs [hunk 1]
```diff
@@ -217,7 +217,10 @@ impl RSAPrivateKey {
                 let res = CRTValue {
                     exp: BigInt::from_biguint(Plus, &self.d % (prime - BigUint::one())),
                     r: BigInt::from_biguint(Plus, r.clone()),
-                    coeff: BigInt::from_biguint(Plus, r.clone().mod_inverse(prime).unwrap()),
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 2]
```diff
@@ -217,7 +217,10 @@ impl RSAPrivateKey {
...
+                    coeff: BigInt::from_biguint(
+                        Plus,
```
Comment (jarlungoodoo73) [inline src/key.rs]: Add

File: src/key.rs [hunk 3]
```diff
@@ -360,18 +363,16 @@ pub fn decrypt<R: Rng>(
     priv_key: &RSAPrivateKey,
     c: &BigUint,
 ) -> Result<BigUint> {
-    if c > priv_key.n() {
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 4]
```diff
@@ -360,18 +363,16 @@ pub fn decrypt<R: Rng>(
...
     }
 
     if priv_key.n().is_zero() {
         return Err(Error::Decryption);
     }
 
-    let mut c = c.clone();
     let mut ir = None;
-
-    if let Some(ref mut rng) = rng {
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 5]
```diff
@@ -360,18 +363,16 @@ pub fn decrypt<R: Rng>(
...
+    let c = if let Some(ref mut rng) = rng {
```
Comment (jarlungoodoo73) [inline src/key.rs]: Add

File: src/key.rs [hunk 6]
```diff
@@ -391,24 +392,32 @@ pub fn decrypt<R: Rng>(
 
         let e = priv_key.e();
         let rpowe = r.modpow(&e, priv_key.n()); // N != 0
-        c = (c * &rpowe) % priv_key.n();
-    }
+        (c * &rpowe) % priv_key.n()
+    } else {
```
Comment (jarlungoodoo73) [inline src/key.rs]: Add

File: src/key.rs [hunk 7]
```diff
@@ -391,24 +392,32 @@ pub fn decrypt<R: Rng>(
...
+        c.clone()
```
Comment (jarlungoodoo73) [inline src/key.rs]: Add

File: src/key.rs [hunk 8]
```diff
@@ -391,24 +392,32 @@ pub fn decrypt<R: Rng>(
...
+    };
 
     let m = match priv_key.precomputed {
         None => c.modpow(priv_key.d(), priv_key.n()),
         Some(ref precomputed) => {
             // We have the precalculated values needed for the CRT.
-            let mut m = BigInt::from_biguint(Plus, c.modpow(&precomputed.dp, &priv_key.primes[0]));
-            let mut m2 = BigInt::from_biguint(Plus, c.modpow(&precomputed.dq, &priv_key.primes[1]));
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 9]
```diff
@@ -496,21 +505,23 @@ mod tests {
         assert_eq!(public_key.e().to_u64(), Some(200));
     }
 
-    fn test_key_basics(private_key: RSAPrivateKey) {
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 10]
```diff
@@ -496,21 +505,23 @@ mod tests {
...
-        private_key.validate().expect("failed to validate");
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 11]
```diff
@@ -496,21 +505,23 @@ mod tests {
...
+    fn test_key_basics(private_key: &RSAPrivateKey) {
+        private_key.validate().expect("invalid private key");
 
         assert!(
             private_key.d() < private_key.n(),
             "private exponent too large"
         );
 
         let pub_key: RSAPublicKey = private_key.clone().into();
-        let m = BigUint::from_u64(42).unwrap();
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 12]
```diff
@@ -496,21 +505,23 @@ mod tests {
...
+        let m = BigUint::from_u64(42).expect("invalid 42");
         let c = encrypt(&pub_key, &m);
-        let m2 = decrypt::<ThreadRng>(None, &private_key, &c).unwrap();
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 13]
```diff
@@ -496,21 +505,23 @@ mod tests {
...
+        let m2 = decrypt::<ThreadRng>(None, &private_key, &c)
+            .expect("unable to decrypt without blinding");
         assert_eq!(m, m2);
         let mut rng = thread_rng();
-        let m3 = decrypt(Some(&mut rng), &private_key, &c).unwrap();
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 14]
```diff
@@ -519,14 +530,17 @@ mod tests {
             #[test]
             fn $name() {
                 let mut rng = thread_rng();
-                let private_key = if $multi == 2 {
-                    RSAPrivateKey::new(&mut rng, $size).unwrap()
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/key.rs [hunk 15]
```diff
@@ -519,14 +530,17 @@ mod tests {
...
-                } else {
-                    generate_multi_prime_key(&mut rng, $multi, $size).unwrap()
-                };
```
Comment (jarlungoodoo73) [inline src/key.rs]: Delete

File: src/lib.rs [hunk 16]
```diff
@@ -1,5 +1,4 @@
-#![doc(html_logo_url =
```
Comment (jarlungoodoo73) [inline src/lib.rs]: Delete

File: src/lib.rs [hunk 17]
```diff
@@ -1,5 +1,4 @@
...
-    "https://raw.githubusercontent.com/RustCrypto/meta/master/logo_small.png")]
+#![doc(html_logo_url = "https://raw.githubusercontent.com/RustCrypto/meta/master/logo_small.png")]
```
Comment (jarlungoodoo73) [inline src/lib.rs]: Add
